### ISSUE TITLE
Access to special tokens ids: BOS, EOS, UNK and PAD

### ISSUE THREAD

**Issue by janpfeifer** [eliben/go-sentencepiece#5]
hi Eli,

First, thanks a lot for putting this together. I'm working on porting Gemma to [GoMLX](https://github.com/gomlx/gomlx) and go-sentencepiece saved some time already.

Something I'm missing to do the sampler is some of the special tokens, that [according to the C++ source code](https://github.com/google/sentencepiece/blob/master/src/model_interface.cc#L31C24-L31C36), are also available in the original proto, and presumably saved in the `tokenizer.model` file (or wherever the sentencepiece model is loaded from).

Namely, the "bos" (BeginningOfSentece), "eos" (EndOfSentence), "pad" and "unk" (Unknown). 

I hope it is ok I created this as a feature request.

cheers

ps.: Notice the Python API has the corresponding `bos_id`, `eos_id`, `unk_id` and `pad_id` methods.

**Comment by eliben** [comment]
Can you clarify what you need, exactly? Just access to these token values or their IDs?

A sketch of usage would help

**Comment by eliben** [comment]
I've pushed a new commit that provides this information. The API is slightly different because I wanted to avoid API polution with all these accessor methods, but it's simple enough (see [test](https://github.com/eliben/go-sentencepiece/blob/main/processor_test.go#L217)).

Please let me know if this works for you, and I'll tag a new release.

**Comment by janpfeifer** [comment]
Thank you @eliben ! It works perfectly.

**Comment by eliben** [comment]
Thank you for confirming; I've tagged v0.5.0 so this should now be available in `go get ...@latest`

**Comment by janpfeifer** [comment]
[My dependency is also updated](https://github.com/gomlx/gemma), and I'm already using the new version in my development.
